fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

pfa_main:
    resource: "@PfaMainBundle/Controller/"
    type:     annotation
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

