# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    pfa.form.registration:
        class: Pfa\SecurityBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: pfa_user_registration }
    pfa.form.profile:
        class: Pfa\SecurityBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: pfa_user_profile }
